name: mapdn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - arrow==1.4.0
      - cloudpickle==3.1.2
      - deepdiff==8.6.1
      - filelock==3.20.0
      - fsspec==2025.12.0
      - geojson==3.2.0
      - grpcio==1.76.0
      - gym==0.26.2
      - jinja2==3.1.6
      - lark==1.3.1
      - llvmlite==0.46.0
      - markdown==3.10
      - markupsafe==2.1.5
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==2.2.6
      - orderly-set==5.5.0
      - packaging==25.0
      - pandapower==3.3.0
      - pandas==2.3.3
      - pandera==0.26.1
      - pillow==12.0.0
      - protobuf==6.33.2
      - pydantic==2.12.5
      - pyglet==2.1.11
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvirtualdisplay==3.0
      - pyyaml==6.0.3
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboardx==2.6.4
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - werkzeug==3.1.4
