name: mapdn
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4777abc_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-aarch64=2.45=default_h1979696_104
  - libexpat=2.7.3=hfae3067_0
  - libffi=3.5.2=hd65408f_0
  - libgcc=15.2.0=h8acb6b2_16
  - libgcc-ng=15.2.0=he9431aa_16
  - libgomp=15.2.0=h8acb6b2_16
  - liblzma=5.8.1=h86ecc28_2
  - libnsl=2.0.1=h86ecc28_1
  - libsqlite=3.51.1=h022381a_0
  - libuuid=2.41.2=h1022ec0_1
  - libxcrypt=4.4.36=h31becfc_1
  - libzlib=1.3.1=h86ecc28_2
  - ncurses=6.5=ha32ae93_3
  - openssl=3.6.0=h8e36d6e_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=h28be5d3_2_cpython
  - readline=8.3=hb682ff5_0
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_h561c983_103
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=h85ac4a6_6
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - arrow==1.4.0
      - cloudpickle==3.1.2
      - deepdiff==8.6.1
      - filelock==3.20.0
      - fqdn==1.5.1
      - fsspec==2025.12.0
      - geojson==3.2.0
      - grpcio==1.76.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jsonpointer==3.0.0
      - lark==1.3.1
      - llvmlite==0.46.0
      - markdown==3.10
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - numba==0.63.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - orderly-set==5.5.0
      - packaging==25.0
      - pandapower==3.3.0
      - pandas==2.3.3
      - pandera==0.26.1
      - pillow==12.0.0
      - pip-autoremove==0.10.0
      - protobuf==6.33.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyglet==2.1.11
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyvirtualdisplay==3.0
      - pyyaml==6.0.3
      - rfc3987-syntax==1.1.0
      - scipy==1.15.3
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tinycss2==1.4.0
      - torch==2.9.0+cu128
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tqdm==4.67.1
      - triton==3.5.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - werkzeug==3.1.4
